### ISSUE TITLE
Comparison with stringify

### ISSUE THREAD

**Issue by domoritz** [codeandcats/fast-clone#9]
How does this function perform in comparison with `JSON.parse(JSON.stringify(obj))`?

**Comment by codeandcats** [comment]
It will be comparable to performing a `JSON.parse(JSON.stringify(obj))` alone, as that's actually what it does behind the scenes. But it then does a quick walk over your object to fix up a bunch of values that the `JSON.parse(JSON.stringify(obj))` stuffs up, like dates, regexs, numbers that are NaN, Infinity, undefined, etc.

**Comment by domoritz** [comment]
Ahh, cool. Thanks for the clarification. I was wondering whether I should switch to a different method but `JSON.parse(JSON.stringify(obj))` works for me so I'll stick with it.

**Comment by codeandcats** [comment]
I just ran some more benchmarks. If performance is absolutely paramount to you and you know you will not have edge cases like those mentioned above then that might be your best option as performing a native `JSON.parse(JSON.stringify(obj))` averages about half the time that fast-clone does. 😃

Otherwise if you may have values like dates, etc I'd recommend using a library for cloning (doesn't have to be this one).
